apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-service
      service: application-service
  template:
    metadata:
      labels:
        app: application-service
        service: application-service
    spec:
      containers:
        - name: challenges2-application-service
          image: challengescontainerregistry.azurecr.io/challenges2-auth-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: production-secret
---

apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: challenges2
spec:
  type: ClusterIP
  selector:
    app: application-service
  ports:
    - protocol: TCP
      port: 3081
