apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: challenges2
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: api-gateway-service
        image: challengescontainerregistry.azurecr.io/challenges2-api-gateway:ci
        ports:
          - containerPort: 3080

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: challenges2
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3080
