version: '3.8'

services:
  node:
    container_name: challenges2_frontend
    build:
      context: ../app
      target: deployment
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "5173:5173"
    volumes:
      - ../app:/app
      - /app/node_modules
