version: '3.8'

services:
  api:
    build: 
      context: ../api
      dockerfile: Dockerfile
    container_name: challengeS2-api
    restart: always
    volumes:
      - ../api:/app
    ports:
      - '3000:3000'
