version: '3.8'

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: challengeS2-api
    volumes:
      - ../api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3080:3080'
