version: '3.8'

services:
  api:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: challenges2_api-gateway
    env_file:
      - ../.env
    volumes:
      - ../api-gateway:/app
      - /app/node_modules
    ports:
      - '3080:3080'
