version: '3.8'

services:
  analytics-service:
    build:
      context: ../services/analytics
      dockerfile: Dockerfile
    container_name: challenges2_analytics-service
    volumes:
      - ../services/analytics:/app
      - /app/node_modules

  app-service:
    build:
      context: ../services/application
      dockerfile: Dockerfile
    container_name: challenges2_app-service
    env_file:
      - ../.env
    volumes:
      - ../services/application:/app
      - /app/node_modules

  auth-service:
    build:
      context: ../services/authentication
      dockerfile: Dockerfile
    container_name: challenges2_authentication-service
    env_file:
      - ../.env
    volumes:
      - ../services/authentication:/app
      - /app/node_modules

  mailing-service:
    build:
      context: ../services/mailing
      dockerfile: Dockerfile
    container_name: challenges2_mailing-service
    env_file:
      - ../.env
    volumes:
      - ../services/mailing:/app
      - /app/node_modules
    ports:
      - "3023:3023"

  mailcatcher:
    image: schickling/mailcatcher
    container_name: challenges2_mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
