version: '3.8'

services:
  app-service:
    build:
      context: ../services/application
      dockerfile: Dockerfile
    container_name: challenges2_app-service
    env_file:
      - ../.env
    volumes:
      - ../services/application:/app
      - /app/node_modules

  auth-service:
    build:
      context: ../services/authentication
      dockerfile: Dockerfile
    container_name: challenges2_authentication-service
    env_file:
      - ../.env
    volumes:
      - ../services/authentication:/auth-service
      - /auth-service/node_modules
    
  quiz-service:
    build:
      context: ../services/quiz
      dockerfile: Dockerfile
    container_name: challenges2_quiz-service
    env_file:
      - ../.env
    volumes:
      - ../services/quiz:/quiz-service
      - /quiz-service/node_modules

  mailing-service:
    build:
      context: ../services/mailing
      dockerfile: Dockerfile
    container_name: challenges2_mailing-service
    env_file:
      - ../.env
    volumes:
      - ../services/mailing:/mailing-service
      - /mailing-service/node_modules
    ports:
      - "3023:3023"

  mailcatcher:
    image: schickling/mailcatcher
    container_name: challenges2_mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
