version: '3.8'

services:
  node:
    container_name: challenges2_frontend
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../app:/app
