version: '3.7'

services:
  node:
    container_name: challengeS2-frontend
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../app:/app
