version: '3.8'

services:
  adminer:
    container_name: challenges2_adminer
    image: adminer
    ports:
      - "8081:8080"

  postgres:
    image: postgres:15.2-alpine
    container_name: challengeS2_postgres
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DATABASE_POSTGRES_DB}
      POSTGRES_USER: ${DATABASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    container_name: challenges2_mongodb
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_MONGO_NAME}
    volumes:
      - /data/db
    ports:
      - "27017:27017"

networks:
  default:
    external: true
    name: challengeS2-network
