apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: api-gateway-service
  labels:
    app: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: docking2000/challenges2-api-gateway-service:latest
        ports:
          - containerPort: 3080

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: api-gateway-service
spec:
  type: NodePort
  selector:
    app: api-gateway-service
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3080
      nodePort: 30800
