apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
      service: analytics
  template:
    metadata:
      labels:
        app: analytics
        service: analytics
    spec:
      containers:
        - name: challenges2-api-analytics
          image: challengescontainerregistry.azurecr.io/challenges2-analytics-service:latest
          imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: challenges2
spec:
  type: ClusterIP
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 3081
