apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges2-frontend
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app

    spec:
      containers:
        - name: challenges2-api-gateway
          image: challengescontainerregistry.azurecr.io/challenges2-app-front:ci
