apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges2-authentication
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
      service: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-app
        service: api-gateway-service
    spec:
      containers:
        - name: challenges2-authentication
          image: docking2000/challenges2-auth-service:latest
          env:
            - name: AUTH_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: AUTH_SERVICE_PORT
            - name: AUTH_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: AUTH_SERVICE_HOST
            - name: JSON_WEB_TOKEN_SECRET
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: JSON_WEB_TOKEN_SECRET
