apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges2-frontend
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
      service: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-app
        service: api-gateway-service
    spec:
      containers:
        - name: challenges2-frontend
          image: docking2000/challenges2-node:latest
          ports:
            - containerPort: 5173

