apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges2-authentication
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
      service: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-app
        service: api-gateway-service
    spec:
      containers:
        - name: challenges2-api-gateway
          image: challengescontainerregistry.azurecr.io/challenges2-app-service:ci

