apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges2-application
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
      service: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-app
        service: api-gateway-service
    spec:
      containers:
        - name: challenges2-application
          image: docking2000/challenges2-app-service:latest
          env:
          - name: DATABASE_POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: DATABASE_POSTGRES_DB
          - name: DATABASE_POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: DATABASE_POSTGRES_PASSWORD
          - name: DATABASE_POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: DATABASE_POSTGRES_USER
          - name: DATABASE_POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: DATABASE_POSTGRES_HOST
          - name: APP_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: APP_SERVICE_HOST
          - name: APP_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: APP_SERVICE_PORT
          - name: JSON_WEB_TOKEN_SECRET
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: JSON_WEB_TOKEN_SECRET
