apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges2-frontend
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
      service: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-app
        service: api-gateway-service
    spec:
      initContainers:
        - name: permission-setup
          image: busybox
          command: [ "sh", "-c", "mkdir -p /app/node_modules/.vite/ && chown -R <user>:<group> /app" ]
          securityContext:
            runAsUser: 0  # Set the desired user ID for the init container
            runAsGroup: 0  # Set the desired group ID for the init container
          volumeMounts:
            - name: app-volume
              mountPath: /app
      containers:
        - name: challenges2-api-gateway
          image: challengescontainerregistry.azurecr.io/challenges2-app-front:ci
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          emptyDir: { }
