apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  namespace: challenges2
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-service
          image: docking2000/challenges2-api:latest
          ports:
            - containerPort: 3080
          env:
            - name: CHALLENGE_ENV
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: CHALLENGE_ENV
            - name: DATABASE_POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_POSTGRES_DB
            - name: DATABASE_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_POSTGRES_PASSWORD
            - name: DATABASE_POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_POSTGRES_USER
            - name: DATABASE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_POSTGRES_HOST
            - name: DATABASE_MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_MONGO_USERNAME
            - name: DATABASE_MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_MONGO_PASSWORD
            - name: DATABASE_MONGO_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_MONGO_NAME
            - name: DATABASE_MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_MONGO_URL
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: FRONTEND_URL
            - name: VITE_API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: VITE_API_GATEWAY_URL
            - name: APP_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: APP_SERVICE_HOST
            - name: APP_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: APP_SERVICE_PORT
            - name: AUTH_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: AUTH_SERVICE_HOST
            - name: AUTH_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: AUTH_SERVICE_PORT
            - name: JSON_WEB_TOKEN_SECRET
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: JSON_WEB_TOKEN_SECRET
            - name: MAILING_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: MAILING_SERVICE_HOST
            - name: MAILING_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: MAILING_SERVICE_PORT
            - name: QUIZ_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: QUIZ_SERVICE_HOST
            - name: QUIZ_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: QUIZ_SERVICE_PORT
---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-app-load-balancer
  namespace: challenges2
spec:
  type: LoadBalancer
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 3080
  selector:
    app: api-gateway-app

