apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: challenges2-quiz
          image: docking2000/challenges2-quiz-service:latest
          env:
            - name: DATABASE_MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_MONGO_USERNAME
            - name: DATABASE_MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_MONGO_PASSWORD
            - name: DATABASE_MONGO_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_MONGO_NAME
            - name: DATABASE_MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_MONGO_URL
            - name: QUIZ_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: QUIZ_SERVICE_HOST
            - name: QUIZ_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: QUIZ_SERVICE_PORT
            - name: JSON_WEB_TOKEN_SECRET
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: JSON_WEB_TOKEN_SECRET

---

apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: challenges2
spec:
  type: ClusterIP
  selector:
    app: quiz-service
  ports:
    - protocol: TCP
      port: 3028
      targetPort: 3028
