apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges2-application
  namespace: challenges2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
      service: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-app
        service: api-gateway-service
    spec:
      containers:
        - name: challenges2-application
          image: docking2000/challenges2-app-service:latest

