# mongodb-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: challenges2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodbstorageclass
  resources:
    requests:
      storage: 5Gi  # Adjust this size as per your requirements
