name: Api gateway branch

on:
  push:
    branches: api-gateway

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          target: production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2-api:latest


      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
