name: App service branch

on:
  push:
    branches: app-service

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push application
        id: docker_build_application_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/application
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2-app-service:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
