name: Continuous Integration

on:
  push:
    branches: e2e

jobs:
  EndtoEnd:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          browser: chrome

  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push analytics
        id: docker_build_analytics_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/analytics
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2-bo-analytics:ci

      - name: Build and push application
        id: docker_build_application_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/application
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2_app-service:ci

      - name: Build and push mailing
        id: docker_build_mailing_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/mailing
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2_mailing-service:ci

      - name: Build and push bo-analytics
        id: docker_build_bo-analytics
        uses: docker/build-push-action@v2
        with:
          context: ./bo-analytics
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2-bo-analytics:ci

      - name: Build and push app front
        id: docker_build_app-front
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2_app-front:ci

      - name: Build and push authentication
        id: docker_build_authentication_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/authentication
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2-auth-service:ci

      - name: Build and push api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenges2-api-gateway:ci

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
