name: Continuous Integration

on:
  push:
    branches: kubernetes

jobs:
  authenticateToAzure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az acr login -n challengeRg
          az account set --subscription 5a6e3f3f-c18d-49ce-b626-5c7824f0cfc7
          az aks get-credentials --resource-group challenges2 --name challengeCluster

      - name: Build and push analytics
        id: docker_build_analytics_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/analytics
          push: true
          tags: challenges2acr.azurecr.io/challenges2-analytics-service:ci

      - name: Build and push application
        id: docker_build_application_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/application
          push: true
          tags: challenges2acr.azurecr.io/challenges2-app-service:ci

      - name: Build and push mailing
        id: docker_build_mailing_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/mailing
          push: true
          tags: challenges2acr.azurecr.io/challenges2-mailing-service:ci

      - name: Build and push bo-analytics
        id: docker_build_bo-analytics
        uses: docker/build-push-action@v2
        with:
          context: ./bo-analytics
          push: true
          tags: challenges2acr.azurecr.io/challenges2-bo-analytics:ci

      - name: Build and push app front
        id: docker_build_app-front
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: challenges2acr.azurecr.io/challenges2-app-front:ci

      - name: Build and push authentication
        id: docker_build_authentication_service
        uses: docker/build-push-action@v2
        with:
          context: ./services/authentication
          push: true
          tags: challenges2acr.azurecr.io/challenges2-auth-service:ci

      - name: Build and push api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          push: true
          tags: challenges2acr.azurecr.io/challenges2-api-gateway:ci


      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
